site_name: IdontKnowRoot
site_url: https://root.dianas.cyou/
nav:
    - 前言: index.md
    - 准备: prepare.md
    - 刷机: root.md
    - 优化: better.md
    - 模块: moudle.md
    - 关于: about.md
theme:
  name: material
  language: zh
  # logo: https://github.com/sudoskys/Root/raw/main/logo.png
  palette:
    primary: indigo

markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/gjzsr
plugins:
  - git-authors
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true


repo_url: https://github.com/sudoskys/Root
edit_uri: edit/main/docs/

copyright: Copyright &copy; 集体所有，商用需申请所有引用作者
