site_name: IdontKnowRoot
site_url: https://root.dianas.cyou/
nav:
    - 前言: index.md
    - 准备: prepare.md
    - 刷机: root.md
    - 优化: optimize.md
    - 模块: module.md
    - 内核: kernel.md
    - 关于: about.md
theme:
  name: material
  language: zh
  # logo: https://github.com/sudoskys/Root/raw/main/logo.png
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - toc.integrate
    #- navigation.indexes
    - navigation.top
    - navigation.instant


    
markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/gjzsr
  analytics:
    provider: custom
    property: foobar 


plugins:
  # - git-authors
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - search


repo_url: https://github.com/sudoskys/Root
edit_uri: edit/main/docs/

copyright: Copyright &copy; 集体所有，以商用为目的的引用需遵守引录条目相应的知识协议或申请其作者的授权
