name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      # - run: pip install mkdocs-git-committers-plugin-2
      
      # build docs
      - run: mkdocs build --clean
      # - run: mkdocs gh-deploy --force
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
